# Generated by Django 4.1.4 on 2022-12-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Tests',
        ),
    ]
