# Generated by Django 4.1.4 on 2022-12-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_test_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.tests'),
        ),
    ]
